export const GET_ACCESS_TOKEN_USER_DATA = "GET_ACCESS_TOKEN_USER_DATA";

export const CHANGE_SIGNIN_POPUP_VALUE = "CHANGE_SIGNIN_POPUP_VALUE";
export const CHANGE_COMET_POPUP_VALUE = "CHANGE_COMET_POPUP_VALUE";
export const CHANGE_PLANET_POPUP_VALUE = "CHANGE_PLANET_POPUP_VALUE";
export const CHANGE_MOON_POPUP_VALUE = "CHANGE_MOON_POPUP_VALUE";
export const CHANGE_SATELLITE_POPUP_VALUE = "CHANGE_SATELLITE_POPUP_VALUE";
export const EDIT_COMET_SUCCESS_DATA = "EDIT_COMET_SUCCESS_DATA";

export const SIGNUP_WITH_FACEBOOK = "SIGNUP_WITH_FACEBOOK";
export const SIGNUP_WITH_GOOGLE = "SIGNUP_WITH_GOOGLE";

export const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS";
export const LOGOUT_REQUEST_ERROR = "LOGOUT_REQUEST_ERROR";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILUE = "FORGOT_PASSWORD_FAILUE";

export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUPA_FAILURE";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILUE = "RESET_PASSWORD_FAILUE";

export const SIGNIN_GOOGLE = "SIGNIN_GOOGLE";
export const SIGNIN_FACEBOOK = "SIGNIN_FACEBOOK";

export const DASHBOARD_DATA = "DASHBOARD_DATA";
export const GET_USERS_DATA = "GET_USERS_DATA";
export const ADD_SEARCH_DATA = "SEARCH_DATA";

export const SEARCH_DATA = "SEARCH_DATA";

export const ADD_CONTACT_SUCCESS_DATA = "ADD_CONTACT_SUCCESS_DATA";
export const ADD_CONTACT_DATA = "ADD_CONTACT_DATA";

export const ADD_STAR_DATA = "ADD_STAR_DATA";
export const EDIT_STAR_DATA = "EDIT_STAR_DATA";
export const ADD_STAR_SUCCESS_DATA = "ADD_STAR_SUCCESS_DATA";
export const EDIT_STAR_SUCCESS_DATA = "EDIT_STAR_SUCCESS_DATA";
export const TOTAL_STAR_COUNT = "TOTAL_STAR_COUNT";
export const FIRST_STAR_ID = "FIRST_STAR_ID";

export const ADD_COMET_DATA = "ADD_COMET_DATA";
export const EDIT_COMET_DATA = "EDIT_COMET_DATA";
export const ADD_COMET_SUCCESS_DATA = "ADD_COMET_SUCCESS_DATA";
export const GET_SINGLE_COMET_BY_ID = "GET_SINGLE_COMET_BY_ID";
export const GET_SINGLE_COMET_TEAMS_BY_ID = "GET_SINGLE_COMET_TEAMS_BY_ID";
export const GET_SINGLE_COMET_FILES_BY_ID = "GET_SINGLE_COMET_FILES_BY_ID";
export const GET_ALL_COMETS_BY_USERID = "GET_ALL_COMETS_BY_USERID";
export const TOTAL_COMETS_COUNT = "TOTAL_COMETS_COUNT";
export const FIRST_COMET_ID = "FIRST_COMET_ID";
export const SELECTED_COMET_SUCCESS = "SELECTED_COMET_SUCCESS";

export const ADD_PLANET_DATA = "ADD_PLANET_DATA";
export const EDIT_PLANET_DATA = "EDIT_PLANET_DATA";
export const ADD_PLANET_SUCCESS_DATA = "ADD_PLANET_SUCCESS_DATA";
export const GET_SINGLE_PLANET_BY_ID = "GET_SINGLE_PLANET_BY_ID";
export const GET_SINGLE_PLANET_TEAMS_BY_ID = "GET_SINGLE_PLANET_TEAMS_BY_ID";
export const GET_SINGLE_PLANET_FILES_BY_ID = "GET_SINGLE_PLANET_FILES_BY_ID";
export const EDIT_PLANET_SUCCESS_DATA = "EDIT_PLANET_SUCCESS_DATA";
export const FIRST_PLANET_ID = "FIRST_PLANET_ID";
export const SELECTED_PLANET_SUCCESS = "SELECTED_PLANET_SUCCESS";

export const GET_ALL_PROJECTS_BY_USERID = "GET_ALL_PROJECTS_BY_USERID";
export const GET_ALL_PLANETS_BY_PROJECT_ID = "GET_ALL_PLANETS_BY_PROJECT_ID";
export const GET_ALL_MOON_BY_PLANETS_ID = "GET_ALL_MOON_BY_PLANETS_ID";
export const GET_ALL_SATELLITE_BY_MOONS_ID = "GET_ALL_SATELLITE_BY_MOONS_ID";
export const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
export const GET_SINGLE_PROJECT_BY_ID = "GET_SINGLE_PROJECT_BY_ID";
export const GET_SINGLE_PROJECT_TEAMS_BY_ID = "GET_SINGLE_PROJECT_TEAMS_BY_ID";
export const GET_SINGLE_PROJECT_FILES_BY_ID = "GET_SINGLE_PROJECT_FILES_BY_ID";
export const SELECTED_STAR_SUCCESS = "SELECTED_STAR_SUCCESS";

export const ADD_MOON_DATA = "ADD_MOON_DATA";
export const EDIT_MOON_DATA = "EDIT_MOON_DATA";
export const ADD_MOON_SUCCESS_DATA = "ADD_MOON_SUCCESS_DATA";
export const GET_SINGLE_MOON_BY_ID = "GET_SINGLE_MOON_BY_ID";
export const GET_SINGLE_MOON_TEAMS_BY_ID = "GET_SINGLE_MOON_TEAMS_BY_ID";
export const GET_SINGLE_MOON_FILES_BY_ID = "GET_SINGLE_MOON_FILES_BY_ID";
export const EDIT_MOON_SUCCESS_DATA = "EDIT_MOON_SUCCESS_DATA";
export const FIRST_MOON_ID = "FIRST_MOON_ID";
export const SELECTED_MOON_SUCCESS = "SELECTED_MOON_SUCCESS";

export const GET_ALL_MOON_BY_PLANET_ID = "GET_ALL_MOON_BY_PLANET_ID";
export const GET_PLANET_BY_ID = "GET_PLANET_BY_ID";

export const ADD_SATELLITE_DATA = "ADD_SATELLITE_DATA";
export const GET_MOON_DETAILS_BY_ID = "GET_MOON_DETAILS_BY_ID";
export const EDIT_SATELLITE_DATA = "EDIT_SATELLITE_DATA";
export const ADD_SATELLITE_SUCCESS_DATA = "ADD_SATELLITE_SUCCESS_DATA";
export const ADD_SATELLITE_SUCCESS_ALL_DATA = "ADD_SATELLITE_SUCCESS_ALL_DATA";
export const GET_ALL_SATELLITE_BY_MOON_ID = "GET_ALL_SATELLITE_BY_MOON_ID";
export const GET_SATELLITE_BY_ID = "GET_SATELLITE_BY_ID";
export const GET_SINGLE_SATELLITE_BY_ID = "GET_SINGLE_SATELLITE_BY_ID";
export const GET_SINGLE_SATELLITE_TEAMS_BY_ID =
  "GET_SINGLE_SATELLITE_TEAMS_BY_ID";
export const GET_SINGLE_SATELLITE_FILES_BY_ID =
  "GET_SINGLE_SATELLITE_FILES_BY_ID";
export const EDIT_SATELLITE_SUCCESS_DATA = "EDIT_SATELLITE_SUCCESS_DATA";
export const SELECTED_SATELLITE_SUCCESS = "SELECTED_SATELLITE_SUCCESS";

export const EDIT_PROFILE = "EDIT_PROFILE";

export const DELETE_STAR = "DELETE_STAR";
export const DELETE_COMET = "DELETE_COMET";
export const DELETE_PLANET = "DELETE_PLANET";
export const DELETE_MOON = "DELETE_MOON";
export const DELETE_SATELLITE = "DELETE_SATELLITE";

export const CHECK_STAR_COUNT = "CHECK_STAR_COUNT";
export const CHECK_COMET_COUNT = "CHECK_COMET_COUNT";

export const GET_REALTIME_MESSAGES = "GET_REALTIME_MESSAGES";
export const GET_REALTIME_USERS_REQUEST = "GET_REALTIME_USERS_REQUEST";
export const GET_REALTIME_USERS_SUCCESS = "GET_REALTIME_USERS_SUCCESS";
export const GET_REALTIME_MESSAGES_FAILURE = "GET_REALTIME_MESSAGES_FAILURE";
export const CLEAR_STAR_STATE = "CLEAR_STAR_STATE";
export const CLEAR_PLANET_STATE = "CLEAR_PLANET_STATE";
export const CLEAR_MOON_STATE = "CLEAR_MOON_STATE";
export const GET_STAR_REALTIME_MESSAGES = "GET_STAR_REALTIME_MESSAGES";
export const GET_PLANET_REALTIME_MESSAGES = "GET_PLANET_REALTIME_MESSAGES";
export const GET_MOON_REALTIME_MESSAGES = "GET_MOON_REALTIME_MESSAGES";
export const GET_SATELLITE_REALTIME_MESSAGES =
  "GET_SATELLITE_REALTIME_MESSAGES";

export const CHANGE_PLAN_NAME = "CHANGE_PLAN_NAME";
export const GET_PRODUCTS_ALL_DATA = "GET_PRODUCTS_ALL_DATA";
export const CHANGE_PRICE_ID = "CHANGE_PRICE_ID";
export const CHANGE_PRODUCT_ID = "CHANGE_PRODUCT_ID";
export const CREATE_CUSTOMER_DATA = "CREATE_CUSTOMER_DATA";
export const GET_CONNECT_DATA = "GET_CONNECT_DATA";

export const PLANET_COUNT_DATA = "PLANET_COUNT_DATA";
export const MOON_COUNT_DATA = "MOON_COUNT_DATA";
export const SATELLITE_COUNT_DATA = "SATELLITE_COUNT_DATA";

export const SELECTED_MEMBER = "SELECTED_MEMBER";

export const STORE_STAR_ID = "STORE_STAR_ID";
export const STAR_NAME_FOR_SATELLITE = "STAR_NAME_FOR_SATELLITE";

export const UPCOMEING_STARS_DATA = "UPCOMEING_STARS_DATA";
export const UPCOMEING_STARS_DATA_SUCCESS = "UPCOMEING_STARS_DATA_SUCCESS";
export const UPCOMEING_ADD_STARS_DATA = "UPCOMEING_ADD_STARS_DATA";
export const UPCOMEING_EDIT_STARS_DATA = "UPCOMEING_ADD_EDIT_DATA";
export const UPCOMEING_STARS_OF_USERS = "UPCOMEING_STARS_OF_USERS";
export const SINGLE_UPCOMEING_STARS_DATA = "SINGLE_UPCOMEING_STARS_DATA";
export const UPCOMEING_EDIT_STARS_DATA_SUCCESS =
  "UPCOMEING_EDIT_STARS_DATA_SUCCESS";
export const DELETE_UPCOMEING_STARS = "DELETE_UPCOMEING_STARS";
export const DELETE_UPCOMEING_STARS_SUCCESS = "DELETE_UPCOMEING_STARS_SUCCESS";

export const ARCHIVE_STAR_DATA = "ARCHIVE_STAR_DATA";
export const ARCHIVE_STAR_DATA_OF_USER = "ARCHIVE_STAR_DATA_OF_USER";
export const ADD_ARCHIVE_STAR_SUCCESS = "ADD_ARCHIVE_STAR_SUCCESS";

export const TERMS_AND_SERVICES = "TERMS_AND_SERVICES";
export const PRIVACY_POLICY = "PRIVACY_POLICY";

export const GET_USER_NOTIFICATION = "GET_USER_NOTIFICATION";
export const MARK_AD_READ_NOTIFICATION = "MARK_AD_READ_NOTIFICATION";
export const CLEAR_COMET_STATE = "CLEAR_COMET_STATE";
export const CLEAR_SATELLITE_STATE = "CLEAR_SATELLITE_STATE";

export const GET_UPCOMING_COMET = "GET_UPCOMING_COMET";
export const UPCOMING_COMET_OF_USERS = "UPCOMEING_COMET_OF_USERS";
export const DELETE_UPCOMEING_COMET = "DELETE_UPCOMEING_COMET";
export const SINGLE_UPCOMEING_COMET_DATA = "SINGLE_UPCOMEING_COMET_DATA";
export const GET_ARCHIVE_COMETS = "GET_ARCHIVE_COMETS";
export const GET_ARCHIVE_COMETS_OF_SUERS = "GET_ARCHIVE_COMETS_OF_SUERS";

export const GET_SUBSCRIPTION_DATA = "GET_SUBSCRIPTION_DATA";
export const GET_SUBSCRIPTION_DATA_OF_USER = "GET_SUBSCRIPTION_DATA_OF_USER";

export const CANCEL_SUBSCRIPTION = "CANCEL_SUBSCRIPTION";

export const GET_ARCHIVE_PLANETS = "GET_ARCHIVE_PLANETS";
export const GET_ARCHIVE_PLANETS_OF_SUERS = "GET_ARCHIVE_PLANETS_OF_SUERS";

export const GET_ARCHIVE_MOONS = "GET_ARCHIVE_MOONS";
export const GET_ARCHIVE_MOONS_OF_SUERS = "GET_ARCHIVE_MOONS_OF_SUERS";

export const GET_ARCHIVE_SATELLITE = "GET_ARCHIVE_SATELLITE";
export const GET_ARCHIVE_SATELLITE_OF_SUERS = "GET_ARCHIVE_SATELLITE_OF_SUERS";

export const GET_EXPIRED_PROJECT_DATA = "GET_EXPIRED_PROJECT_DATA";
export const GET_EXPIRED_PROJECT_DATA_ALL = "GET_EXPIRED_PROJECT_DATA_ALL";
export const GET_MOONS_ALL_DATA_BY_PLANT = "GET_MOONS_ALL_DATA_BY_PLANT";
export const GET_SATELLITE_OF_MOON_OF_USERS = "GET_SATELLITE_OF_MOON_OF_USERS";

export const ADD_STAR_REQUEST = "ADD_STAR_REQUEST";
export const ADD_STAR_FAIL = "ADD_STAR_FAIL";
export const PLANTES_ALL_DATA = "PLANTES_ALL_DATA";

export const ADD_PLANET_REQUEST = "ADD_PLANET_REQUEST";
export const ADD_PLANET_FAIL = "ADD_PLANET_FAIL";

export const ADD_MOON_REQUEST = "ADD_MOON_REQUEST";
export const ADD_MOON_FAIL = "ADD_MOON_FAIL";

export const ADD_SATELLITE_REQUEST = "ADD_SATELLITE_REQUEST";
export const ADD_SATELLITE_FAIL = "ADD_SATELLITE_FAIL";

export const ADD_COMET_REQUEST = "ADD_COMET_REQUEST";
export const ADD_COMET_FAIL = "ADD_COMET_FAIL";

export const GET_COMET_OF_USERS_ALL = "GET_COMET_OF_USERS_ALL";

export const GET_EXPIRED_COMET_DATA = "GET_EXPIRED_COMET_DATA";
export const GET_EXPIRED_COMET_DATA_ALL = "GET_EXPIRED_COMET_DATA_ALL";

export const GET_EXPIRED_PLANET_DATA = "GET_EXPIRED_PLANET_DATA";
export const GET_EXPIRED_PLANET_DATA_ALL = "GET_EXPIRED_PLANET_DATA_ALL";

export const GET_EXPIRED_MOONS_DATA = "GET_EXPIRED_MOONS_DATA";
export const GET_EXPIRED_MOONS_DATA_ALL = "GET_EXPIRED_MOONS_DATA_ALL";

export const GET_EXPIRED_SATELLITE_DATA = "GET_EXPIRED_SATELLITE_DATA";
export const GET_EXPIRED_SATELLITE_DATA_ALL = "GET_EXPIRED_SATELLITE_DATA_ALL";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const REQUEST_EVENT_DATA = "REQUEST_EVENT_DATA";
export const FAIL_EVENT_DATA = "FAIL_EVENT_DATA";

export const STORE_NOTIFI_COUNT = "STORE_NOTIFI_COUNT";
